### ISSUE TITLE
Appropriate REST service to "call" from tests.

### ISSUE THREAD

**Issue by yahirah** [yahirah/Responsum-Test-Framework#12]
I would like to have the services that allow me to:
- call given company
- stop the call

For now, I don't think I need more, do I, @rostgaard?

**Comment by rostgaard** [comment]
I'll get right on it, as soon as I'm not bogged down by DTU course-stuff (Thursday+ seems realistic).
I can provide you with either high-level the macros - such as the ones you described - or, just expose the existing API.

This effectively means that you would have to a bit more work, but it will be more flexible in the end.

The above example would then correspond to the following pseudo-code;

Caller caller = HTTP.Post (somehost/customerpool/aquire)
Call call = HTTP.Post (caller/{caller.ID}/dial/{extension})
HTTP.Post (call/{call.ID}/hangup)

Alternatively; you could just ask to kick-start a use case and I'll allocate the resources needed and return them to you.

So; 
UseCase uc = HTTP.Post (use_case/{id}/run)
User u = uc.user
Reception r = uc.reception
...

Makes sense?

**Comment by yahirah** [comment]
The question is, do I really need to have a detailed API? From what I understand from use cases, it's calling this or other company and hanging out, those two actions, so low-level framework may not be something useful in this case.
Although I appreciate use-case dedicated API, I think it's better to create something that can be reused later for different projects/parts.

**Comment by rostgaard** [comment]
I'm thinking. Could you, to get started, perform the dial-in and hangups manually?
We could also provide you with a (remote-controllable) hardware phone that is bound to a real PSTN number?

**Comment by yahirah** [comment]
M... it can be hard, but doable. But hard.

**Comment by rostgaard** [comment]
OK then. I think I have a solution proposition which I hopefully can deploy on the openreception server tomorrow. Ping me on GTalk tomorrow afternoon if you don't hear anything.
