### ISSUE TITLE
Create POM for Login.

### ISSUE THREAD

**Issue by yahirah** [yahirah/Responsum-Test-Framework#2]
This POM should have all login buttons &fields with optional "accept" button for new users.

**Comment by rostgaard** [comment]
There are no login input fields or buttons as of now.  The Dart code detects that it cannot connect to our websocket and transfers the client to our OAuth provider (Google) and does a OAuth dance back to our authentication server which creates a neat little authentication token for future use.

The token is stored in the callback URL (settoken GET parameter), and the client configuration is available here; http://service.openreception.org/configuration

**Comment by yahirah** [comment]
The google login website is what I call login buttons.

**Comment by yahirah** [comment]
Workload: 0,5h.
