### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by yahirah** [yahirah/Responsum-Test-Framework#6]
If at one point I can be introduced to the god forsaken coding that is used in the website, so I can start using String comparison instead of length comparison, I would be sooo happy. Because apparently: "BitStackers" != "BitStackers" and welcome text is: Velkommen til BitStackers, hvad kan jeg hj?lpe med?. Right now I think I'm on utf-8 and it seems not to be working.

**Comment by rostgaard** [comment]
It's Unicode (utf-8). I even think we managed to get the Postgres to use it as well. The correct string should be; Velkommen til BitStackers, hvad kan jeg hjælpe med?

Also, string length will probably differ if you treat the Unicode string as Latin-?.
Fun on a bun.

**Comment by yahirah** [comment]
The issue was that after some project copying magic I didn't set my whole IDE to utf-8 again, like I should (it was cp-1250) and mvn was also not set. And ofc some java magic I forgot about: (text == text2) != (text.equals(text2)) - that was the "BitStackers" issue.
